---

- name: Install dependencies (Debian)
  apt:
    name: "{{ item }}"
    update_cache: true
  loop:
    - openssl
    - git

- name: Download easy-rsa
  git:
    repo: https://github.com/OpenVPN/easy-rsa
    dest: /tmp/easy-rsa/
    version: "{{ easyrsa_version }}"

- name: Install library files
  copy:
    src: /tmp/easy-rsa/easyrsa3/
    dest: /usr/local/lib/easyrsa
    remote_src: true
    mode: 0o755
    owner: root
    group: root

- name: Set permissions
  file:
    path: /usr/local/lib/easyrsa/
    state: directory
    recurse: true
    mode: o+rX

- name: Install binary
  copy:
    content: |
      #!/usr/bin/env bash
      /usr/local/lib/easyrsa/easyrsa --vars=/usr/local/lib/easyrsa/vars "$@"
    dest: /usr/local/bin/easyrsa
    mode: 0o755
    owner: root
    group: root
